name: User Report
description: Report Exploiters or Serious TOS Violators
title: "[REPORT] "
labels: Report
assignees: adudu21isme

body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        **Reporting guidelines (to make it easier to review)**
        > Clear proof of the user exploiting or Violating Serious TOS.
        > Press ESC to open the roblox ESC menu, show their username and click their username in the in-game playerlist.
        > 20+ Seconds Full Screen Recording (recommended), show that you are not using any executors (open task manager and show every process, if you are trusted by adudu21, you don't have to do this.).
        **Additional information**
        > If your report doesn't contain sufficient evidence, it will be closed/denied.
        > Before reporting, ensure the user isn't already on the [list](https://raw.githubusercontent.com/adudu21isme/rbxrulebreakers/refs/heads/main/users).
  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement of Reporting guidelines
      options:
        - label: I have followed the reporting guidelines.
          required: true
        - label: I have verified the user is not already in the list.
          required: true
  - type: input
    id: user
    attributes:
      label: UserId or Username (reported user)
      description: "UserId is preferred, find their account via the roblox website and the URL will contain their userid (example:roblox.com/users/1/profile)"
      placeholder: "1"
    validations:
      required: true
  - type: input
    id: evidence
    attributes:
      label: Video Evidence (Youtube or Discord)
      description: "If your video is long, please mention at what timestamp the evidence is at in Additional information."
      placeholder: "https://www.youtube.com/watch?v=video"
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: If you want to provide additional information, provide it here. Otherwise, just leave it empty.
      value: "N/A"
