name: User Report
description: Report rule breakers
title: "[REPORT] "
labels: Report
assignees: adudu21isme

body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        **Reporting guidelines (so its easier to review)**
        > Clear proof of the user violating the rules (read README.md for information).
        > Open the roblox menu (ESC menu), show their username and click their username aswell in the ingame playerlist.
        > 20+ Seconds Full Screen Recording (recommended), show that you are not using any executors (open task manager, if you are trusted by adudu21, you don't have to do this).
        **Additional information**
        > If your report doesn't contain sufficient information, it will be denied.
        > Before reporting, ensure the user isn't already on the [list](https://raw.githubusercontent.com/adudu21isme/rbxrulebreakers/refs/heads/main/users).
        > Reports are read if reported on GitHub or proper ways to contact adudu21.

        
        > [!CAUTION]
        > YOUR REPORT CANNOT CONTAIN ILLEGAL MATERIAL (SUCH AS CSAM, ZOOPHILIA AND SUCH)
        > It is recommended that you use [![Discord](https://img.shields.io/badge/Discord-black.svg?logo=Discord&logoColor=white)](https://discord.gg/U7JstgHdyg) to report instead
  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement of Reporting guidelines
      options:
        - label: I have acknowledged the reporting guidelines.
          required: true
        - label: I have verified the user is not already in the list.
          required: true
  - type: input
    id: user
    attributes:
      label: UserId or Username
      description: "UserId is preferred, find their account via the roblox website and the URL will contain their userid (example:roblox.com/users/1/profile)"
      placeholder: "1/Roblox"
    validations:
      required: true
  - type: input
    id: evidence
    attributes:
      label: Video Evidence (Youtube, Streamable, Discord)
      description: "If video is long, mention at what timestamp the evidence is at via Additional information."
      placeholder: "https://www.youtube.com/watch?v=kOyEVP7B-jc"
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: If you want to provide additional information, provide it here. Otherwise, just leave it empty.
      value: "N/A"
